name: Publish to TestPyPI 🧪

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build tools 🔧
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package 📦
      working-directory: ./aiclient
      run: python -m build

    - name: Publish to TestPyPI 🧪
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages_dir: aiclient/dist/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip_existing: true
